# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainMenu(object):
    def setupUi(self, mainMenu):
        mainMenu.setObjectName("mainMenu")
        mainMenu.resize(440, 309)
        self.menuTitle = QtWidgets.QLabel(mainMenu)
        self.menuTitle.setGeometry(QtCore.QRect(20, 20, 411, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.menuTitle.setFont(font)
        self.menuTitle.setAutoFillBackground(False)
        self.menuTitle.setScaledContents(False)
        self.menuTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.menuTitle.setObjectName("menuTitle")
        self.testingButton = QtWidgets.QPushButton(mainMenu)
        self.testingButton.setGeometry(QtCore.QRect(30, 70, 131, 41))
        self.testingButton.setObjectName("testingButton")
        self.dataButton = QtWidgets.QPushButton(mainMenu)
        self.dataButton.setGeometry(QtCore.QRect(30, 130, 131, 41))
        self.dataButton.setObjectName("dataButton")
        self.hardwareButton = QtWidgets.QPushButton(mainMenu)
        self.hardwareButton.setGeometry(QtCore.QRect(30, 190, 131, 41))
        self.hardwareButton.setObjectName("hardwareButton")
        self.pushButton_4 = QtWidgets.QPushButton(mainMenu)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 260, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.hardwareLabel = QtWidgets.QLabel(mainMenu)
        self.hardwareLabel.setGeometry(QtCore.QRect(180, 200, 201, 20))
        self.hardwareLabel.setObjectName("hardwareLabel")
        self.dataLabel = QtWidgets.QLabel(mainMenu)
        self.dataLabel.setGeometry(QtCore.QRect(180, 140, 201, 20))
        self.dataLabel.setObjectName("dataLabel")
        self.testingLabel = QtWidgets.QLabel(mainMenu)
        self.testingLabel.setGeometry(QtCore.QRect(180, 70, 231, 31))
        self.testingLabel.setObjectName("testingLabel")

        self.retranslateUi(mainMenu)
        QtCore.QMetaObject.connectSlotsByName(mainMenu)

    def retranslateUi(self, mainMenu):
        _translate = QtCore.QCoreApplication.translate
        mainMenu.setWindowTitle(_translate("mainMenu", "Optical BioSensor Controller"))
        self.menuTitle.setText(_translate("mainMenu", "Main Menu"))
        self.testingButton.setText(_translate("mainMenu", "Testing"))
        self.dataButton.setText(_translate("mainMenu", "Data"))
        self.hardwareButton.setText(_translate("mainMenu", "Hardware "))
        self.pushButton_4.setText(_translate("mainMenu", "Logout"))
        self.hardwareLabel.setText(_translate("mainMenu", "Status of Current Hardware Connections"))
        self.dataLabel.setText(_translate("mainMenu", "View Data Recorded from Previous Tests"))
        self.testingLabel.setText(_translate("mainMenu", "Run a diagnostic test to receive a major result"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainMenu = QtWidgets.QWidget()
    ui = Ui_mainMenu()
    ui.setupUi(mainMenu)
    mainMenu.show()
    sys.exit(app.exec_())
