# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestingPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(625, 415)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.testinglabel = QtWidgets.QLabel(self.centralwidget)
        self.testinglabel.setGeometry(QtCore.QRect(240, 20, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.testinglabel.setFont(font)
        self.testinglabel.setObjectName("testinglabel")
        self.resultlabel = QtWidgets.QLabel(self.centralwidget)
        self.resultlabel.setGeometry(QtCore.QRect(250, 190, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.resultlabel.setFont(font)
        self.resultlabel.setAutoFillBackground(False)
        self.resultlabel.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.resultlabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.resultlabel.setLineWidth(5)
        self.resultlabel.setObjectName("resultlabel")
        self.CSlabel = QtWidgets.QLabel(self.centralwidget)
        self.CSlabel.setGeometry(QtCore.QRect(80, 100, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.CSlabel.setFont(font)
        self.CSlabel.setObjectName("CSlabel")
        self.TSlabel = QtWidgets.QLabel(self.centralwidget)
        self.TSlabel.setGeometry(QtCore.QRect(170, 250, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.TSlabel.setFont(font)
        self.TSlabel.setObjectName("TSlabel")
        self.MRlabel = QtWidgets.QLabel(self.centralwidget)
        self.MRlabel.setGeometry(QtCore.QRect(160, 290, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.MRlabel.setFont(font)
        self.MRlabel.setObjectName("MRlabel")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(410, 100, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.button1.setFont(font)
        self.button1.setAutoFillBackground(True)
        self.button1.setObjectName("button1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 625, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.testinglabel.setText(_translate("MainWindow", "TESTING"))
        self.resultlabel.setText(_translate("MainWindow", "RESULT"))
        self.CSlabel.setText(_translate("MainWindow", "Cartridge Status:"))
        self.TSlabel.setText(_translate("MainWindow", "Test Status:"))
        self.MRlabel.setText(_translate("MainWindow", "Major Result:"))
        self.button1.setText(_translate("MainWindow", "Run Test"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
